### ISSUE TITLE
Remove special code for facet_*

### ISSUE THREAD

**Issue by depristo** [sirrice/pygg#11]
facet_grid and facet_wrap have a special API right now to handle the formulas in R.  Update the code so that the interface isn't specialized and you use the functions directly with escaped strings:

Today:

```
p = p + facet_grid('x', 'y')
```

Proposed API:

```
p = p + facet_grid(esc("x ~ y"))
```

**Comment by sirrice** [comment]
What do you think of escaping in the background?

```
p = p + facet_grid("x ~ y")
```

**Comment by depristo** [comment]
It'd be fine but those two functions will have slightly different apis than all other functions that have to pass in strings.  I'd recommend against it, but it's up to you

**Comment by sirrice** [comment]
We goofed -- escaping not needed.
