### ISSUE TITLE
name collision with `matplotlib.pyplot`

### ISSUE THREAD

**Issue by tacaswell** [sirrice/pygg#2]
The name `pyplot` has been is use by matplotlib sense 2007, this is going to cause great confusion.

_This_ `pyplot` should probably be renamed (and removed from pipy under this name).

attn @mdboom @efiring

**Comment by sirrice** [comment]
Thanks for letting me know.  Renamed to avoid collision and removed from pipy.  

Sorry about that!  Completely forgot about matplotlib.pyplot when naming.

**Comment by tacaswell** [comment]
Thank you so much for being understanding and accommodating, we really
appreciate it.
